name = "AlgebraicStatistics"
uuid = "eaf2fd51-3dbe-4b59-888d-69232a6d440a"
authors = ["Tobias Boege <post@taboege.de>", "Benjamin Hollering <benhollering@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
